### ISSUE TITLE
Can't get your code to work properly

### ISSUE THREAD

**Issue by MattSpeakman** [wenhuix/si7005-in-RaspberryPI#1]
Hi,
I have just tried to get your code to work however I only ever get a RH of 100.000. I am using a new Raspberry Pi 2 Model B with the latest Raspbian

**Comment by MattSpeakman** [comment]
Forget that. Did a hard reset of my Pi and now it is giving me a normal reading!! Must have been a glitch in the Matrix!

**Comment by wenhuix** [comment]
I'm glad to hear it's working right :)
